#!/bin/bash
current_dir=`realpath .`
working_dir=$current_dir
#working_dir=$current_dir
#echo $working_dir
if [ $# = 0 ]; then
	echo give proper file name
	exit
elif [ -d $1 ]; then
	#echo r
	working_dir=`realpath $1`
	rm -r target_dir
	mkdir target_dir
	target_dir=`realpath target_dir`
	if [ -f $2 ]; then
		input_file=$2
	else
		echo give proper input file
		exit
	fi
elif [ -f $1 ]; then
	input_file=$1
	rm -r ../target_dir
	mkdir ../target_dir
	target_dir=`realpath target_dir`
else
	echo give proper input file
fi

#main_dir=`realpath $working_dir/..`
#rm -r $main_dir/target_dir
#mkdir target_dir




#echo $working_dir $input_file

first=`head -1 $input_file`
second=`head -2 $input_file | tail -1`
third=`tail -1 $input_file`

#g=`grep -ni u $input_file`
#echo $g

#echo $first
#echo $working_dir



file_name=""


main_dir=`realpath $working_dir/..`
#rm -r $main_dir/target_dir
#mkdir target_dir
name=""
flag="1"
f(){
	cd $1
	if [ $flag = "1" ];then
		name=$1\.
		flag="0"
	else name=$name$1\.
	fi
	
	#echo at dir $1
	list=`ls` 
	for ff in $list
	do
		#echo $ff
		if [ -d $ff ]; then
			f $ff
		elif [ -f $ff ]; then
			#str=`head -n 1 $ff | grep -ni "f1"`
			#echo $str
			#echo file paisi $ff name er
			str=`file $ff | grep -i "ascii"`
			str2=`file $ff | grep -i "unicode"`
			command=""
			if [ -z "$str" ] && [ -z "$str2" ]; then
				echo $ff not readable						
			elif [ $first = "begin" ];then
				command=`head -n $second $ff | grep -n $third`
#				if [ ! -z "$command" ]; then
#					echo $ff contains $third
#				else echo $ff does not contains $third
#				fi
			elif [ $first = "end" ];then
				command=`tail -n $second $ff | grep -n $third`
			fi
			 	
			if [ ! -z "$command" ]; then
				dot=`echo $ff | grep "\."`
				if [ $first = "end" ]; then
					num=`grep -n . "$ff" | grep "$third" | tail -1 | cut -f 1 -d :`
				else num=`grep -n . "$ff" | grep "$third" | head -1 | cut -f 1 -d :`
				fi
#				echo num : $num line.
				ff1=""
				if [ ! -z "$dot" ]; then
					ff1=$($ff/"."/".$num")
				else ff1=$ff$num
				fi
				echo $ff contains $third
#				echo "com : $command"
#				echo $target_dir/$name$ff
				echo from : $ff
				echo to : "$target_dir/$name$ff1"
				sudo cp -a $ff "$target_dir/$name$ff1"
			else echo $ff does not contains $third
			fi
			
		fi
	done	
	cd ..	
}

f $1


