#!/bin/bash
current_dir=`realpath .`
working_dir=$current_dir
file_no=`expr 0`
#working_dir=$current_dir
#echo $working_dir
if [ $# = 0 ]; then
	echo give proper file name
	exit
elif [ -d "$1" ]; then
	#echo r
	working_dir_name=$1
	working_dir=`realpath $1`
	rm -r target_dir
	mkdir target_dir
	target_dir=`realpath target_dir`
	if [ -f "$2" ]; then
		input_file=$2
		first=`head -1 $input_file`
		second=`head -2 $input_file | tail -1`
		third=`tail -1 $input_file`
	else
		echo give proper input file
		exit
	fi
elif [ -f "$1" ]; then

	input_file=$1
	rm -r ../target_dir
	mkdir ../target_dir
	target_dir=`realpath target_dir`
	temp=`realpath .`
	working_dir_name=`basename $temp`
	cd ..
	
	first=`head -1 $working_dir_name/$input_file`
	second=`head -2 $working_dir_name/$input_file | tail -1`
	third=`tail -1 $working_dir_name/$input_file`
	
else
	echo give proper input file
fi

rm $target_dir/../out.csv
touch $target_dir/../out.csv
echo File path,Line number,File containing the searched text > out.csv
file_name=""


main_dir=`realpath $working_dir/..`
#rm -r $main_dir/target_dir
#mkdir target_dir
name=""
flag="1"
f(){
	cd "$1"
#	if [ $flag = "1" ];then
#		name=$1\.
#		flag="0"
#	else name=$name$1\.
#	fi
	
#	echo at dir $1
	list=`ls` 
	for ff in *
	do
		
		if [ -d "$ff" ]; then
#			echo at : $ff
			f "$ff"
		elif [ -f "$ff" ]; then
#			echo at file : $ff
			#str=`head -n 1 $ff | grep -ni "f1"`
			#echo $str
			#echo file paisi $ff name er
			str=`file $ff | grep -i "ascii"`
			str2=`file $ff | grep -i "unicode"`
			command=""
			if [ -z "$str" ] && [ -z "$str2" ]; then
				status=`echo $ff not readable`
#				echo $status
			elif [ $first = "begin" ];then
				command=`head -n $second $ff | grep -ni $third`
#				if [ ! -z "$command" ]; then
#					echo $ff contains $third
#				else echo $ff does not contains $third
#				fi
			elif [ $first = "end" ];then
				command=`tail -n $second $ff | grep -ni $third`
			fi
			 	
			if [ ! -z "$command" ]; then
				dot=`echo $ff | grep "\."`
				if [ $first = "end" ]; then
					num=`grep -n . "$ff" | grep -i "$third" | tail -1 | cut -f 1 -d :`
					the_line=`grep . "$ff" | grep -i "$third" | tail -1`
				else num=`grep -n . "$ff" | grep -i "$third" | head -1 | cut -f 1 -d :`
					the_line=`grep . "$ff" | grep -i "$third" | head -1`
				fi
				
#				echo num : $num line.
				ff1=""
				if [ ! -z "$dot" ]; then
					#ff1=$($ff/"."/".$num")
					num2=`echo $num | rev`
					ff1=`echo $ff | rev | sed "s|\.|\.$num2|" | rev`
				else ff1=$ff$num
				fi
#				echo $ff contains $third
#				echo new name : $ff1
#				echo "com : $command"
#				echo $target_dir/$name$ff
				#echo w : $working_dir
				rep=$working_dir
				name=`realpath . | sed "s|^.*$working_dir_name|$working_dir_name|"`
				name=`echo $name | sed "s|/|\.|g"`
#				echo nam : $name
#				echo from : $ff
#				echo to : "$target_dir/$name.$ff1"
				sudo cp -a $ff "$target_dir/$name.$ff1"
				file_no=`expr $file_no + 1`
#				echo file_no : $file_no
				echo $name/$ff,$num,$the_line >> $target_dir/../out.csv
			else status2=`echo $ff does not contains $third`
			fi
			
		fi
	done	
	cd ..	
}

f $working_dir_name
echo total files matched : $file_no 
#echo $file_no, ,  >> $target_dir/../out.csv

