import subprocess
out = subprocess.run('sh test.sh', shell=True, capture_output=True)
val = out.stdout.decode()
print(val)
print(ord(val[0]), ord(val[1]))
print(ord(val[2]), ord(val[3]))
print(ord(val[4]), ord(val[5]))
print(ord(val[6]), ord(val[7]))
print()
# print(ord(val[8]), ord(val[9]))
print(ord(val[10]), ord(val[11]))
print(ord(val[12]), ord(val[13]))
print(ord(val[14]), ord(val[15]))
print(ord(val[16]), ord(val[17]))

