#!/bin/bash
current_dir=`realpath .`
working_dir="$current_dir"
file_no=0 				

if [ $# = 0 ]; then
	echo give proper input file name
	exit
elif [ -d "$1" ]; then
	temp=`realpath "$1"`
	working_dir_name=`basename "$temp"`		
	working_dir=`realpath "$1"`

	if [ -f "$2" ]; then
		input_file="$2"

	else
		echo give proper input file name
		exit
	fi
elif [ -f "$1" ]; then

	input_file="$1"
	temp=`realpath .`
	working_dir_name=`basename "$temp"`

	
else
	echo give proper input file
fi

rm -r "$working_dir"/../target_dir
mkdir "$working_dir"/../target_dir
target_dir=`realpath "$working_dir"/../target_dir`

rm "$target_dir"/../out.csv
touch "$target_dir"/../out.csv
echo File path,Line number,Line containing the searched text > "$working_dir"/../out.csv
file_name=""

first=`head -1 "$input_file"`
second=`head -2 "$input_file" | tail -1`
third=`tail -1 "$input_file"`


main_dir=`realpath "$working_dir"/..`
name=""

f(){
	cd "$1"
	list=`ls` 
	for ff in *
	do
		
		if [ -d "$ff" ]; then
#			echo at : $ff
			f "$ff"
		elif [ -f "$ff" ]; then
#			echo at file : "$ff"
			str=`file "$ff" | grep -i "ascii"`
			str2=`file "$ff" | grep -i "unicode"`
			command=""
#			echo str : "$str"
#			echo str2 : "$str2"
			if [ -z "$str" ] && [ -z "$str2" ]; then
				status=`echo "$ff" not readable`
#				echo $status
			elif [ "$first" = "begin" ];then
				command=`head -n "$second" "$ff" | grep -ni "$third"`
#				echo com : $command
			elif [ "$first" = "end" ];then
				command=`tail -n "$second" "$ff" | grep -ni "$third"`
			fi
			 	
#			echo com : $command 	
			if [ ! -z "$command" ]; then
#				echo found
				dot=`echo "$ff" | grep "\."`
				if [ "$first" = "end" ]; then
					num=`grep -n . "$ff" | grep -i "$third" | tail -1 | cut -f 1 -d :`
					the_line=`grep . "$ff" | grep -i "$third" | tail -1`
				else num=`grep -n . "$ff" | grep -i "$third" | head -1 | cut -f 1 -d :`
					the_line=`grep . "$ff" | grep -i "$third" | head -1`
				fi
#				echo num : "$num"
				ff1=""
				if [ ! -z "$dot" ]; then
					num2=`echo "$num" | rev`
					ff1=`echo "$ff" | rev | sed "s|\.|\."$num2"|" | rev`
				else ff1="$ff""$num"
				fi
				rep="$working_dir"
				name=`realpath . | sed "s|"$working_dir"|"$working_dir_name"|"`
				name=`echo "$name" | sed "s|/|\.|g"`
				sudo cp -a "$ff" "$target_dir"/"$name"."$ff1"
				file_no=`expr "$file_no" + 1`
#				echo file_no : $file_no
				
#				echo \""$name"/"$ff"\",\""$num"\",\""$the_line"\" >> "$target_dir"/../out.csv
				line_cnt=`more "$ff" | grep -i "$third" | wc -l | cut -f 1 -d ' '`
#				line_cnt=0
				if [ "$second" -le "$line_cnt" ]; then
					mn=$second
				else mn=$line_cnt	
				fi
				for (( i=1; i<="$mn"; i++ ))
				do
					if [ "$first" = "end" ]; then
						num2=`grep -n . "$ff" | grep -i "$third" | tail -"$second" | head -"$i" | tail -1 | cut -f 1 -d :`
						the_line=`grep . "$ff" | grep -i "$third" | tail -"$second" | head -"$i" | tail -1`
					else num2=`grep -n . "$ff" | grep -i "$third" | head -"$i" | tail -1 | cut -f 1 -d :`
						the_line=`grep . "$ff" | grep -i "$third" | head -"$i" | tail -1`
					fi
#					echo num2 : $num2
#					echo line : $the_line
					echo \""$name"/"$ff"\",\""$num2"\",\""$the_line"\" >> "$target_dir"/../out.csv
					
				done
				
			else status2=`echo "$ff" does not contains "$third"`
#				echo not found
			fi
			
		fi
	done	
	cd ..	
}

f "$working_dir"
echo total files matched : "$file_no" 
#echo $file_no, ,  >> $target_dir/../out.csv

